### PR TITLE
chore: bump node version to 18.x for ci

### PR DESCRIPTION
**Pull request by chouchouji**

### CODE REVIEW

**Comment by iosh** [comment]
Hi can you update `actions/setup-node` and `actions/checkout` ?

**Comment by chouchouji** [comment]
> actions/setup-node

I check the version of them

image

Do you mean that I should change v3 to v4?

image

**Comment by chouchouji** [comment]
> Yes.

done

**Review by iosh — APPROVED** [review]
Thanks @chouchouji .

**Comment by chouchouji** [comment]
If the #191 is merged, the lowest node version should be 18.x. We have increased the node version to 18.x in ci. I think it is good to add `engine` to `package.json` and  update  `readme.md`.

**Comment by iosh** [comment]
> > If the #191 is merged, the lowest node version should be 18.x. We have increased the node version to 18.x in ci. I think it is good to add `engine` to `package.json` and update `readme.md`.
> 
> I think I can add this changes to #191. What do you think? @iosh

OK.

**Pull request merged**
