### PR TITLE
refactor: remove process.js

### LINKED ISSUE #204: [Improvement] optimize node process code
Should we remove `process.js` file?  We can replace it with 

```ts
const process = require('node:process')
```

image

image

### PR DESCRIPTION
**Pull request by chouchouji**
close #204

### CODE REVIEW

**Comment by chouchouji** [comment]
I am confused that why did it fail

image

**Comment by iosh** [comment]
I'll check it later.

**Comment by chouchouji** [comment]
> I'll check it later.

Thanks. In theory, I modified the way the node module is introduced, and the test case should not go wrong.

**Comment by chouchouji** [comment]
> I am confused that why did it fail
> 
> image

I try my another branch. 

image

**Comment by chouchouji** [comment]
It is amazing. I removed `const process = require('node:process')`, all test cases have passed.

**Comment by iosh** [comment]
I will check this.  don't worry, Maybe i will migrate the test to vitest, I am  use jest less frequently.

**Comment by chouchouji** [comment]
> I will check this. don't worry, Maybe i will migrate the test to vitest, I am use jest less frequently.

Me too, I use vitest.

**Comment by chouchouji** [comment]
> I will check this. don't worry, Maybe i will migrate the test to vitest, I am use jest less frequently.

Will this repo migrate to typescript in a major version?

**Comment by iosh** [comment]
> > I will check this. don't worry, Maybe i will migrate the test to vitest, I am use jest less frequently.
> 
> Will this repo migrate to typescript in a major version?

I think we can migrate to typescript. This is good thing and won't affect user usage.

**Comment by chouchouji** [comment]
> > > I will check this. don't worry, Maybe i will migrate the test to vitest, I am use jest less frequently.
> > 
> > 
> > Will this repo migrate to typescript in a major version?
> 
> I think we can migrate to typescript. This is good thing and won't affect user usage.

👍🏻

**Comment by chouchouji** [comment]
> > > I will check this. don't worry, Maybe i will migrate the test to vitest, I am use jest less frequently.
> > 
> > 
> > Will this repo migrate to typescript in a major version?
> 
> I think we can migrate to typescript. This is good thing and won't affect user usage.

When will this work start? I am pleased to work for it.

**Comment by iosh** [comment]
> > > > I will check this. don't worry, Maybe i will migrate the test to vitest, I am use jest less frequently.
> > > 
> > > 
> > > Will this repo migrate to typescript in a major version?
> > 
> > 
> > I think we can migrate to typescript. This is good thing and won't affect user usage.
> 
> When will this work start? I am pleased to work for it.

How about when we merge the recent changes ?

**Comment by chouchouji** [comment]
> > > > > I will check this. don't worry, Maybe i will migrate the test to vitest, I am use jest less frequently.
> > > > 
> > > > 
> > > > Will this repo migrate to typescript in a major version?
> > > 
> > > 
> > > I think we can migrate to typescript. This is good thing and won't affect user usage.
> > 
> > 
> > When will this work start? I am pleased to work for it.
> 
> How about when we merge the recent changes ?

I think I can add a issue.

**Comment by chouchouji** [comment]
I think we should close this pr. The #208 contains it.

**Pull request closed without merging**
