### PR TITLE
chore: update v2

### PR DESCRIPTION
**Pull request by iosh**

### CODE REVIEW

**Comment by iosh** [comment]
@chouchouji Please review this.

**Comment by iosh** [comment]
> > @chouchouji Please review this.
> 
> LGTM. Should we add a lint workflow to check files?

Yes，we can add a lint workflow.

**Comment by chouchouji** [comment]
I think we can add a clean script in package.json after merging this pr. It is helpful to delete node_modules and dist folder.

**Comment by iosh** [comment]
The [rimraf](https://www.npmjs.com/package/rimraf) package looks good, It is cross-platfrom

**Comment by chouchouji** [comment]
> > I think we can add a clean script in package.json after merging this pr. It is helpful to delete node_modules and dist folder.
> 
> why we need delete the node_modules.

Sometimes, node modules cache may affect the normal work.

**Comment by chouchouji** [comment]
> The [rimraf](https://www.npmjs.com/package/rimraf) package looks good, It is cross-platfrom

Yes, it is a good choice. Many famous repos are using it.

**Comment by iosh** [comment]
> > > I think we can add a clean script in package.json after merging this pr. It is helpful to delete node_modules and dist folder.
> > 
> > 
> > why we need delete the node_modules.
> 
> Sometimes, node modules cache may affect the normal work.

OK, let me merge this PR.

**Comment by iosh** [comment]
> I will submit a pr to complete this work (add clean script).

Thank you very much.

**Pull request merged**
