### PR TITLE
feat: allow to select from registry list if name is undefined

### LINKED ISSUE #187: [Improvement] nrm use supports select
# QUESTION

Sometimes, I don't remember the list of npm registries. While using `nrm use` command,  I don't enter registry name alias, it will show error.  How about changing this behavior? If you don't enter registry npm alias, the terminal can provide a registry list for user to select. I think it can improve development experience.

### PR DESCRIPTION
**Pull request by chouchouji**
# Issue

close #187 

# Result

https://github.com/user-attachments/assets/2c55425a-690b-4377-bca7-140f5efdb882

### CODE REVIEW

**Comment by chouchouji** [comment]
@iosh  I had complete the feature. But I am good at writing test cases. Can you help me?

**Comment by iosh** [comment]
> @iosh I had completed the feature. But I am good at writing test cases. Can you help me?

Do you mean that you're not good at writing tests? If so, I can help you. but I will need some time to do this.

**Comment by chouchouji** [comment]
> > @iosh I had completed the feature. But I am good at writing test cases. Can you help me?
> 
> Do you mean that you're not good at writing tests? If so, I can help you. but I will need some time to do this.

Yes. I try to add test case. But I failed......

**Comment by chouchouji** [comment]
I forget to ask how to update readme. It is necessary to add `nrm use` tip for users.

**Comment by chouchouji** [comment]
The ci had failed.  The lowest version of node is 18.x for most versions of `Inquirer.js` .  Shall we increase node version in ci? 

image

**Comment by iosh** [comment]
@chouchouji  Node 16 is end of  life, So  i will update the node version in CI to 18(this weekend).

**Comment by chouchouji** [comment]
> @chouchouji Node 16 is end of life, So i will update the node version in CI to 18(this weekend).

**Comment by chouchouji** [comment]
sorry, I clicked close. Can you reopen it. Thanks!

**Comment by chouchouji** [comment]
> @chouchouji Node 16 is end of life, So i will update the node version in CI to 18(this weekend).

Is it enough to just modify the node version in ci? If it is, I am pleased to submit a pr.

**Comment by iosh** [comment]
> sorry, I clicked close. Can you reopen it. Thanks!

Sorry, I can't reopen this PR as the button is disabled and it says "The feat-use branch was force-pushed or recreated." I think you might need to create a new PR.



> > @chouchouji Node 16 is end of life, So i will update the node version in CI to 18(this weekend).
> 
> Is it enough to just modify the node version in ci? If it is, I am pleased to submit a pr.

I think so, we can try for this.

**Comment by chouchouji** [comment]
> > sorry, I clicked close. Can you reopen it. Thanks!
> 
> Sorry, I can't reopen this PR as the button is disabled and it says "The feat-use branch was force-pushed or recreated." I think you might need to create a new PR.
> 
> > > @chouchouji Node 16 is end of life, So i will update the node version in CI to 18(this weekend).
> > 
> > 
> > Is it enough to just modify the node version in ci? If it is, I am pleased to submit a pr.
> 
> I think so, we can try for this.

The new pr is #191. Thanks.

**Pull request closed without merging**
