### PR TITLE
WIP: Refactor nrm

### PR DESCRIPTION
**Pull request by CaptainOfPhB**
This is a **Work In Progress** merge request, **CAN NOT** merge directly now.

### Motivation

When I tried to add some test cases for `cli.js`, I found some test cases will run fail for some reason, [for example](https://github.com/CaptainOfPhB/nrm/commit/f8248513ee97cdd950f21ef3cab3d892a4f5f0c3), `npm.config.get('registry')` will get a wrong registry(`https://registry.yarnpkg.com/`) sometimes, I am sure about that the registry(`https://registry.yarnpkg.com/`) does not exist in any related configuration file.

In addition, use `npm` lib to write `.npmrc`file is unnecessary, `fs.writeFileSync` is enough. And the programmatic API was removed in`npm` from v8.0.0, as we can see in [`index.js`](https://github.com/npm/cli/blob/de45f90eebbf51205748ed3f09fbeab6cc000b3e/index.js#L4), so, the `var npm = require('npm')` usage is not recommended and already has been deprecated.

### I will do

- remove `npm` dependency
- replace `request` with `node-fetch`
- split project files and make the code more concise
- add more test cases

### CODE REVIEW

**Comment by CaptainOfPhB** [comment]
please review @i5ting

**Comment by i5ting** [comment]
1、tap测试是没有问题
2、test-console用起来没有coffee用的直观
3、可以把sinon引入，理解一下spies，stubs，mocks，测试用例代码看着可读性还需要提升。

**Comment by CaptainOfPhB** [comment]
1. test-console 可以测试单个函数的输出，看了下 coffee，类似于 child_process，直接从命令行作为入口，测试输出，这和测试单个函数并无明显区别。
2. tap 已具备 mock 功能，虽然没有 sinon 断言 spy 函数被调用的功能，但是通过 test-console 测试 mock 函数的输出也可以达到同样的效果，即 mock 的函数被调用了。

**Comment by i5ting** [comment]
功能是类似的，可读性上是有差异的。另外我理解coffee对跨平台做了很多兼容。

tap的mock功能我还没看到，https://github.com/tapjs/node-tap/blob/main/package.json#L22依赖有点多。

先合并，一点点优化吧

**Comment by CaptainOfPhB** [comment]
OK，谢狼叔指点。

**Pull request merged**
