### PR TITLE
feat: support deleting multiple custom registries

### LINKED ISSUE #215: [Feature] Support deleting multiple custom registries
# Question 

I have three useless custom registry. I want to delete all of them. But I have to delete one by one.  I think it is helpful to support deleting multiple registries. 

image

# Solution

image

[https://github.com/SBoudrias/Inquirer.js/tree/main/packages/checkbox](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/checkbox)

### PR DESCRIPTION
**Pull request by chouchouji**
# Issue
close #215 

# Result
https://github.com/user-attachments/assets/6d05e94d-bc25-4ec5-b321-d155dc0dd976

### CODE REVIEW

**Comment by chouchouji** [comment]
@iosh I have implemented the need, Please add test cases in this pr. Thanks.

**Comment by iosh** [comment]
Sorry, I will review it as soon as possible (been a bit busy lately).

**Comment by iosh** [comment]
> @iosh I have implemented the need, Please add test cases in this pr. Thanks.

OK, but not sure if it can be completed this week.

**Comment by chouchouji** [comment]
> Sorry, I will review it as soon as possible (been a bit busy lately).

Thanks.

**Comment by chouchouji** [comment]
> > @iosh I have implemented the need, Please add test cases in this pr. Thanks.
> 
> OK, but not sure if it can be completed this week.

I think this task is not urgent. We can complete it when you are free.

**Comment by iosh** [comment]
@chouchouji  Please review this when you have time . Thanks.

**Comment by chouchouji** [comment]
> @chouchouji Please review this when you have time . Thanks.

LGTM.

**Review by iosh — APPROVED** [review]

**Pull request merged**
