### PR TITLE
release 2.0

### PR DESCRIPTION
**Pull request by iosh**

### CODE REVIEW

**Comment by iosh** [comment]
@chouchouji Let us review again for this.

**Comment by chouchouji** [comment]
image
It is strange.

**Comment by iosh** [comment]
> image It is strange.

Yes, i am checking.

**Comment by iosh** [comment]
I have update the code and test， you can see there why the test is changed.
**https://github.com/SBoudrias/Inquirer.js/blob/5713287885155c0081fca4190c17c18c598d9602/packages/select/src/index.ts#L212**

**Comment by chouchouji** [comment]
> I have update the code and test， you can see there why the test is changed. **https://github.com/SBoudrias/Inquirer.js/blob/5713287885155c0081fca4190c17c18c598d9602/packages/select/src/index.ts#L212**

LGTM

**Review by chouchouji — APPROVED** [review]

**Comment by chouchouji** [comment]
I think we should update release ci.

**Comment by chouchouji** [comment]
```yml
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: pnpm i
```

**Pull request merged**
