### PR TITLE
docs: update example in readme

### PR DESCRIPTION
**Pull request by chouchouji**

### CODE REVIEW

**Comment by iosh** [comment]
HI  @chouchouji  please add you to Contributors in readme.

**Comment by chouchouji** [comment]
> HI @chouchouji please add you to Contributors in readme.

image
like this?

**Comment by iosh** [comment]
> > HI @chouchouji please add you to Contributors in readme.
> 
> image like this?

Yes.

**Comment by iosh** [comment]
> > > > HI @chouchouji please add you to Contributors in readme.
> > > 
> > > 
> > > image like this?
> > 
> > 
> > Yes.
> 
> Should we use this url https://contrib.rocks/image?repo=Pana/nrm in image? It should contain all of us.
> 
> image

ok to me.

**Comment by chouchouji** [comment]
> > > > > HI @chouchouji please add you to Contributors in readme.
> > > > 
> > > > 
> > > > image like this?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Should we use this url https://contrib.rocks/image?repo=Pana/nrm in image? It should contain all of us.
> > image
> 
> ok to me.

Done. Please review. Thanks.

**Review by iosh — APPROVED** [review]
Thanks.

**Comment by chouchouji** [comment]
Hi, @iosh. I want to ask a question. Do we have this registry `nodejitsu`?

**Comment by iosh** [comment]
> Hi, @iosh. I want to ask a question. Do we have this registry `nodejitsu`?

No, I think we don't have this registry , we can remove it from readme.

**Comment by chouchouji** [comment]
> > Hi, @iosh. I want to ask a question. Do we have this registry `nodejitsu`?
> 
> No, I think we don't have this registry , we can remove it from readme.

 I optimize the readme in #213. Please review.

**Pull request merged**
