### PR TITLE
feat: support switching registry locally

### LINKED ISSUE #48: Can nrm hold  difference  setting between global and local
when I type: "nrm use cnpm", all the project will switch to this registry. 
I just want to set local project switch that, don't effect other project's registry,
that mean you could seperate global and local setting.
could you provide extract command to do that, like:
nrm use cnpm -global
nrm use xxx -local

### PR DESCRIPTION
**Pull request by chouchouji**
# Issue

close #48 

# Result

https://github.com/user-attachments/assets/45bd82f9-1e42-4580-9ccc-5441ff49c187

### CODE REVIEW

**Comment by chouchouji** [comment]
The pr is leak of docs and test cases. I will add them in recent days.

**Comment by chouchouji** [comment]
@iosh Can you add test cases in this branch?

**Comment by iosh** [comment]
> @iosh Can you add test cases in this branch?

Yes(I need wait unit weekend to do this)

**Comment by chouchouji** [comment]
> > @iosh Can you add test cases in this branch?
> 
> Yes(I need wait unit weekend to do this)

Ok. You can add test cases in my current branch. Thanks a lot.

**Comment by chouchouji** [comment]
When will you release `v1.4.1`?

**Comment by iosh** [comment]
> When will you release `v1.4.1`?

I think we can wait this pr to merge ?

**Comment by chouchouji** [comment]
> > When will you release `v1.4.1`?
> 
> I think we can wait this pr to merge ?

Ok, I get it. Thanks.

**Comment by chouchouji** [comment]
Thanks @iosh. I had merged test pr.

**Review by iosh — APPROVED** [review]

**Pull request merged**
